name: google-test

on: push

jobs:
  test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
    - name: Action
      uses: actions/checkout@v2
    - name: Compile the tests and code
      run: make
    - name: Run the tests
      run: ./runTests 